### ISSUE TITLE
[Bug] Mod Not Working 

### ISSUE THREAD

**Issue by 123ghaksd** [sleepingdragoninn/antique-atlas#130] opened 2024-06-07 16:09 UTC
Mod seems to be loaded under "Mod Menu" but is not loaded in the creative menu, JEI, is not craftable, and cannot even do /give.

Also have issues in previous version. (2.8.2)

Mod Loader: Fabric
Mod Version: 2.9.0
MC Version: 1.20.1

**Comment by sleepingdragoninn** [comment] 2024-06-07 21:58
duplicate of #53, #90

**Closed as not planned by sleepingdragoninn** 2024-06-07 21:58 UTC
