### ISSUE TITLE
Crash with ChoiceTheorem's Overhauled Village

### ISSUE THREAD

**Issue by TomBCosmos** [sleepingdragoninn/antique-atlas#160] opened 2024-07-07 09:17 UTC
Server experiences often crashes. Upon server restart, after the crash, I am unable to connect due to "**java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "p_236859_" is null**", even though the server is online.

I have to remove the mod from both server and client, After which I can join the server no problem.

But because I really like this mod and there's nothing rivals it, I then re-add the mod to both server and client and it works again for about 20 minutes before crashing again and repeating all the above.

From the crash report, it suspects the culprit is the embedded mod within Antique Atlas "Surveyor Map Framework (surveyor), Version: 0.6.31.20". But I am not sure how correct that is as I am no pro at reading crash logs.

Minecraft version: 1.20.1
Forge version: 47.3.0
Java Version: 17.0.8
Antique Atlas version: 2.9.9+1.20

[latest.log](https://github.com/user-attachments/files/16118651/latest.log)

[crash-2024-07-07_08.43.27-server.txt](https://github.com/user-attachments/files/16118652/crash-2024-07-07_08.43.27-server.txt)

**Comment by TomBCosmos** [comment] 2024-07-07 10:10
Update:

I had seen that today, there was a release for Antique Atlas version 2.9.10+1.20.

I have already tried this but exact same issue still occurs.

**Comment by sleepingdragoninn** [comment] 2024-07-07 11:07
Can't reproduce in pure - I think one of your mods is either adding a structure with a field that is never missing in vanilla, or completely breaking how the registry system works.

Here's a version that tries to work around this [surveyor-0.6.7-why-on-earth-would-a-registry-key-have-a-null-identifier+1.20.jar.zip](https://github.com/user-attachments/files/16118932/surveyor-0.6.7-why-on-earth-would-a-registry-key-have-a-null-identifier%2B1.20.jar.zip) - give it a try and let me know

**Comment by TomBCosmos** [comment] 2024-07-07 11:35
Thank you for the quick response.

Unfortunately, adding that version of surveyor crashed the server before it could even get far into loading process (it did not produce a crash report so I have copy pasted what happened in the console). 

It also crashes my client before it fully loads Forge.

[Server Crash.txt](https://github.com/user-attachments/files/16118979/Server.Crash.txt)
[latest.log](https://github.com/user-attachments/files/16118981/latest.log)

Apologies if this is asking too much, but is there a way to tell which structures or mods are causing that "never missing in vanilla" or breaking of the registry issue? Or is it the classic, remove mods until it doesn't happen type of thing?

As removing the mods and testing will take the rest of day considering it takes 20 - 30 mins for the crash to happen if it even will :(

**Comment by sleepingdragoninn** [comment] 2024-07-07 13:30
sounds like you have a much larger problem with your instance than surveyor if i'm honest - without a reliable way to produce a usable log, there's not much we can do. There's a mod clogging something for sure.

**Comment by TomBCosmos** [comment] 2024-07-07 13:33
Understood, thank you for your time :)

If I ever find out which mod it is that's causing Antique Atlas to fall over, I'll let you know so it can be added as a known compat issue.

**Comment by YOUNIN15** [comment] 2024-07-11 16:02
The same thing is happening to me, were you able to find out what the mod that causes this is.

**Comment by Tuna7822** [comment] 2024-07-12 08:00
Hello there. Got the same issue when trying to connect my modded forge server

Antique Atlas v2.9.11

I can send you my servers logs if you need it.

![image](https://github.com/user-attachments/assets/afdef6fb-08c9-4927-a164-38008b5c8c25)

**Comment by TomBCosmos** [comment] 2024-07-12 16:53
> The same thing is happening to me, were you able to find out what the mod that causes this is.

Unfortunately not.

However, although I did not get a crash log, upon loading a world, this happened only once weirdly enough, but the console gave out a good few errors with to do with Antique Atlas which leads me to believe it is one of these mods:

- Structory
- MVS - Moog's Voyager Structures
- Dungeon Now Loading 1%
- Towns and Towers
- ChoiceTheorem's Overhauled Village
- When Dungeons Arise
- Or any of the structures in the Yung's better series

I have not tested it yet however. So if you have any of the same mods, it could help you narrow it down to just the ones we have in common.

**Comment by sleepingdragoninn** [comment] 2024-07-13 03:51
Looks like this is https://github.com/sisby-folk/surveyor/issues/37 / https://github.com/sisby-folk/antique-atlas/issues/141

**Comment by sleepingdragoninn** [comment] 2024-07-31 10:01
fixed in surveyor 0.6.17

**Closed as completed by sleepingdragoninn** 2024-07-31 10:01 UTC
Labels: incompatibility
