### ISSUE TITLE
Having an issue where I crash when entering the nether.

### ISSUE THREAD

**Issue by SakuraTheSky** [sleepingdragoninn/antique-atlas#153] opened 2024-07-01 05:56 UTC
Not sure if it's specifically just atlas causing it but the fatal error crashing the game keeps mentioning atlas in it.  https://mclo.gs/eJxQT0I

**Comment by sleepingdragoninn** [comment] 2024-07-01 08:48
please update the mod! dupe of #129

**Closed as not planned by sleepingdragoninn** 2024-07-01 08:48 UTC
