### ISSUE TITLE
Does not work on Fabric 1.20.1 Prism Launcher

### ISSUE THREAD

**Issue by Vladikum** [sleepingdragoninn/antique-atlas#226] opened 2024-09-29 12:07 UTC

**Comment by Vladikum** [comment] 2024-09-29 12:08
I still haven't figured out what additional mods need to be installed.

**Comment by sleepingdragoninn** [comment] 2024-09-29 17:07
no info, assumed duplicate of #222 #192 #133 #130 #90 #53

**Closed as not planned by sleepingdragoninn** 2024-09-29 17:07 UTC
