### ISSUE TITLE
Map erased / only markers + small area visible

### ISSUE THREAD

**Issue by mhnu16** [sleepingdragoninn/antique-atlas#170] opened 2024-07-16 15:25 UTC
While playing on a modded server with my friends, I discovered that upon closing the game instance and re-entering the server, all of the area I explored gets deleted, while the markers I made remain.
I'm using "antique-atlas-2.9.12+1.21" and the server contains "surveyor-0.6.11+1.21.jar".

Here is the [latest.log](https://mclo.gs/qtn4eP7).

Example image:
![image](https://github.com/user-attachments/assets/4d40423a-31f3-41cf-a31f-a216fae5d800)

**Comment by mhnu16** [comment] 2024-07-17 21:08
It seems that upon removing surveyor from the server, this bug disappears.

**Comment by sleepingdragoninn** [comment] 2024-07-22 01:18
Can't seem to reproduce this on the same versions - is surveyor still configured default on both sides? 
Does this still occur on a clean server with just antique atlas?

**Comment by amenbr1** [comment] 2024-08-11 08:25
Same issue on LAN.
Everyone had the markers merged and map reset.
Nobody was using share at the time.

**Comment by ArkGrayer** [comment] 2024-08-13 17:49
Having same issue here, when i close game i lost entire map and all markers merges with my client.
Idk why

**Comment by Krimatoria** [comment] 2024-08-18 10:16
+1
![2024-08-18_11 36 03](https://github.com/user-attachments/assets/ded571e0-d1c4-487b-a58f-4d863ebf0d45)

**Comment by SpaceNerd95251** [comment] 2024-09-08 18:34
Just here to say +1, experienced this issue in multiplayer, minecraft version 1.20.1, surveyor version 0.6.23, atlas version 2.9.17

**Comment by Krimatoria** [comment] 2024-09-08 19:53
> Just here to say +1, experienced this issue in multiplayer, minecraft version 1.20.1, surveyor version 0.6.23, atlas version 2.9.17

it doesn't matter if the Surveyor Map Framework is worth it or without it, the same thing.

**Comment by EicoYT** [comment] 2024-09-09 17:17
Its been a while so the logs are somewhere but it would take a lot of time to search for them. 
![Unbenannt2](https://github.com/user-attachments/assets/a012b4f6-6909-4557-acc4-1be30101df97)
I cant say anything to how it happened like other people here but I only noticed after a while of playing I opened the map for the first time and saw that it isnt working and only the starting area is marked.

**Comment by EicoYT** [comment] 2024-09-09 18:14
So I just tested older versions of both Antique Atlas 4 and Surveyor and it seems that if I stop the server after going in a new area and then directly start the server again and join again that area will be drawn on the map, Im doing more tests.

**Comment by EicoYT** [comment] 2024-09-09 18:18
I wanna correct I only have to reconnect and then its drawn

**Comment by EicoYT** [comment] 2024-09-09 18:20
[latest.log](https://github.com/user-attachments/files/16934925/latest.log)
[latest.log](https://github.com/user-attachments/files/16934926/latest.log)
the first is the server log and the second is the client log, I will shortly send a clip and then test the Antique atlas 4 newest version together with the surveyor newest version.

**Comment by EicoYT** [comment] 2024-09-09 18:25
https://medal.tv/games/minecraft/clips/iE89uDpmKYEDlBvH8/d1337jOQkOVO?invite=cr-MSxKZlcsMTM4NjA5NDg5LA

**Comment by sleepingdragoninn** [comment] 2024-09-09 18:26
I appreciate the logs so far, at this point I think what we really need is a reproduction case. If anyone can figure out *when* this happens using a fresh instance and a set of steps, it would be greatly appreciated.

Is this consistently on LAN Share? or does it happen on dedicated as well? can it happen in singleplayer?

**Comment by EicoYT** [comment] 2024-09-09 18:28
I didnt see it happening in singleplayer and if you want I can do testing since it will benefital for me to on a new instance, this is a local server I set up on my pc.

**Comment by EicoYT** [comment] 2024-09-09 18:52
new instance and new server with only these 4 mods
![image](https://github.com/user-attachments/assets/f69e906c-0a66-4077-8625-be2f3c3be5a7)
works, the map loads without problems even after leaving, shutting off server, shutting on server and joining again, works
[latest.log](https://github.com/user-attachments/files/16935217/latest.log)
[latest.log](https://github.com/user-attachments/files/16935220/latest.log)
heres again logs, the first is the server and the second is the client.

**Comment by EicoYT** [comment] 2024-09-09 18:58
dude I dont know anymore, it may be because of an incompatible mod but then how big are the chances all these people have the same incompatible mod, can you tell me where antique atlas and/or surveyor saves their information about whats loaded on the map?

**Comment by sleepingdragoninn** [comment] 2024-09-09 19:00
(redacted for incorrect info, oops, thought this was another issue)

**Comment by EicoYT** [comment] 2024-09-09 19:01
srry, what does that mean? I dont really understand that

**Comment by EicoYT** [comment] 2024-09-09 19:02
does that mean you know what cuases this?

**Comment by sleepingdragoninn** [comment] 2024-09-09 19:13
oops, got this one confused with another issue - ignore me!

**Comment by EicoYT** [comment] 2024-09-09 19:29
alright

**Comment by SpaceNerd95251** [comment] 2024-09-09 21:33
I can at least clarify my earlier comment and say it happened on a dedicated server, not on LAN

**Comment by SpaceNerd95251** [comment] 2024-09-09 22:12
Some more info: I can confirm that things work as normal with singleplayer, even though I used the same instance of Prism as I normally use to join multiplayer. Though I suppose the issue in question could be a server side only mod that I don't have installed. In terms of multiplayer, exiting to the main menu and then rejoining the server works as expected; it is only when I exit to desktop and relaunch the instance that the problem occurs.

I know you have a lot at this point, but here's some logs, just in case it helps:
https://mclo.gs/uS9IRQH
https://mclo.gs/5GEtNDt

**Comment by Krimatoria** [comment] 2024-09-10 10:06
https://github.com/sisby-folk/antique-atlas/issues/180
No it happens in a single player game too

This happens in a single player game and if you just open the world to the network, it doesn't matter. In each game, if you enter the world, the map will draw a part of the explored world. You will exit minecraft and close everything altogether. Then start Minecraft again, you will lose part of the map, most of it sometimes disappear and markers too, in short it is broken + other players who entered your world do not update the map, and the labels and part of the explored territories disappear.

**Comment by sleepingdragoninn** [comment] 2024-09-10 10:12
So to confirm your reproduction steps:
- Create a new world
- Click "open to LAN"
- Save and quit
- Exit the instance
- Restart the instance 
- Reload the same world
- Map appears emptied?

Does this occur in a fresh fabric 1.20.1 instance with just atlas and fapi?

**Comment by Krimatoria** [comment] 2024-09-10 10:24
> So to confirm your reproduction steps:
> 
> * Create a new world
> * Click "open to LAN"
> * Save and quit
> * Exit the instance
> * Restart the instance
> * Reload the same world
> * Map appears emptied?
> 
> Does this occur in a fresh fabric 1.20.1 instance with just atlas and fapi?

I'm just a little busy right now, but the main way is to walk around the world and make TP somewhere far away, put labels there, upload the territory. Not only in the respawn place. I will add screenshots and playback paths before after later. No, I've only tried it with the forge connector.

**Comment by Krimatoria** [comment] 2024-09-11 13:54
> So to confirm your reproduction steps:
> 
> * Create a new world
> * Click "open to LAN"
> * Save and quit
> * Exit the instance
> * Restart the instance
> * Reload the same world
> * Map appears emptied?
> 
> Does this occur in a fresh fabric 1.20.1 instance with just atlas and fapi?

I was playing on the server yesterday, putting tags. 

I'm going to go into the world right now and see how the map has changed.

![2024-09-11_01 11 57](https://github.com/user-attachments/assets/94e1e8ab-abe8-49df-b38a-dec3023ac6a4)
![2024-09-11_01 11 34](https://github.com/user-attachments/assets/bd6490e4-9f5d-415d-ac3f-e8e8c164f744)
![2024-09-11_01 11 39](https://github.com/user-attachments/assets/aa10cdf4-3e38-4127-80da-c5621b26cadf)
By the way, when changing the scale, I noticed another point, there is a label, and the territory is cut off, although if you zoom in it is there, but this is a trifle. 
![2024-09-11_01 11 44](https://github.com/user-attachments/assets/3429b98c-a57c-4b9e-941e-6b17b13634d5)
I specially made enlarged copies of the areas with labels that were far away.
![2024-09-11_01 11 48](https://github.com/user-attachments/assets/34c6f86f-bb30-478e-a6cb-30b02dd11665)

**Comment by Uranus-19AU** [comment] 2024-09-13 15:06
I think dying might be the culprit, or at least one of the culprits. I've found a set of steps that works with just this mod installed (and fabric API), on a fresh instance. It doesn't even require that you close the game - just exiting and re-entering the world will do, so long as you do so after having died during your play session. Here's my log: [https://mclo.gs/IdZiGPl](https://mclo.gs/IdZiGPl)

Recreate steps:
1. Make a new world in creative with cheats enabled, and fly in a straight line for a bit to cover some terrain on the map
3. Die and respawn 
4. Exit the world, and reopen it

You should find that any terrain you had explored is now gone, though any markers you placed will have persisted (such as the grave marker that gets placed automatically). Dying seems to put your game in a state where the map information will be lost upon exiting the world.

This might be an entirely separate bug to the ones that have been mentioned above, so apologies if this isn't the right place to put this.

**Comment by SpaceNerd95251** [comment] 2024-09-13 16:31
The one's in my case werent to do with dying, it would happen whenever I fully closed the instance and relaunched it. Just exiting the world/server did not do anything. I didn't die during my testing, and the map did persist as you'd expect in singleplayer even when exiting and relaunching the game. 

Again this is only in my case, and I haven't yet tried it with just antique atlas + surveyor (cause I don't have a good server to test it on) so it may be affected by mods or something idk

**Comment by SpaceNerd95251** [comment] 2024-09-20 22:55
Update: I just was on my server for a bit, and I suddenly realized that my map is still there from the last session I played (technically two relogs ago, since prism crashed once today so I had to rejoin the server). This is the first time I've seen it not be deleted. I will let you know if I discover more. Maybe a mod was causing this, and whatever mod it was got updated?


Edit: It works. It just works. No idea why or how, but all of a sudden I can't get it to have an issue. It's persisting across fully relaunching and across dimension changes. Only thing I haven't tried is dying

**Comment by Krimatoria** [comment] 2024-09-28 21:25
Is there an update planned to fix this error? At least approximately. @sisby-folk

**Comment by sleepingdragoninn** [comment] 2024-10-01 09:01
Appears to be an underlying issue in surveyor, I've had this reported on hoofprint as well (which tends to be easier to debug)

**Comment by Krimatoria** [comment] 2024-10-01 09:29
> Похоже, это основная проблема Surveyor, мне также сообщили об этом в Hoofprint (который, как правило, легче отладить)

After creating a flat world, I teleported to 1000 blocks, that's what I noticed in the log file.
Start Game 

> [02:10:22] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 1 structure regions, 0 landmarks

When you press pause to open the world to LAN

> [02:10:29] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 2 structure regions, 0 landmarks

Dead + Exit the world without closing the game. Re-entered the world 

> [02:10:53] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 0 structure regions, 1 landmarks

**Comment by Krimatoria** [comment] 2024-10-01 13:23
And what does it mean?
[02:10:22] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 1 structure regions, 0 landmarks
[02:10:29] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 2 structure regions, 0 landmarks
[02:10:53] [Server thread/INFO] [surveyor/]: [Surveyor] Finished saving data for minecraft:overworld | cleaned 4 terrain regions, 0 structure regions, 1 landmarks

**Comment by Fyrelitee** [comment] 2024-10-08 15:44
I'm having the same issue, also noticed that my map got reset except for markers when I opened to LAN and rejoined the world for a single player world. Is there any way to recover the map data from files in the folder? I had explored quite a large area and this is the second time it has happened, it would be a pain to refill it every time.

**Comment by pjon1** [comment] 2024-10-08 16:24
@Fyrelitee
If you have a backup of your world from before losing the data, you can copy it over. You can find it with an nbt editor under `Data.Player.surveyor` in your level.dat file or with `/data get entity @p surveyor` in-game.

**Comment by Fyrelitee** [comment] 2024-10-09 14:20
@pjon1 
Thanks! This worked, i'll just need to make a backup after every 'expedition' until this issue is resolved. For anyone else who finds this solution, https://nbt.mcph.to is a good online nbt editor, like pjon1 said above, in the level.dat file, navigate to Data > Player > surveyor and copy over the data.

**Comment by pjon1** [comment] 2024-10-09 14:42
> i'll just need to make a backup after every 'expedition' until this issue is resolved.

You can try the fix here https://github.com/sisby-folk/surveyor/pull/53#issuecomment-2396277201

**Comment by sleepingdragoninn** [comment] 2024-10-11 13:52
this should be fixed in 2.10 - thanks again @pjon1!

**Closed as completed by sleepingdragoninn** 2024-10-11 13:52 UTC
Labels: bug

**Comment by DMCHiggens** [comment] 2025-06-15 17:52
![Image](https://github.com/user-attachments/assets/f45992ea-fd4f-4240-8b8b-ed476d0b4a5c)

im feeling like this issue may be back in 2.11 
apologies for reviving the thread ^^;

**Comment by Shyvvi** [comment] 2025-09-14 22:33
I'm also having this issue on 1.21.1 Fabric
