### ISSUE TITLE
the map is deleted 1.21 

### ISSUE THREAD

**Issue by grynvych** [sleepingdragoninn/antique-atlas#227] opened 2024-09-30 15:37 UTC
I don't understand why this happens, it can happen during the game (without leaving the game) and in different dimensions
![image](https://github.com/user-attachments/assets/14ec2c15-ad26-4518-8f75-8f563b512223)

if you need to provide any additional data, please let me know
![image](https://github.com/user-attachments/assets/564eb5c3-867b-4db2-93dd-1d973a4a40f3)
![image](https://github.com/user-attachments/assets/b7c40cbc-446e-41b3-b33d-5640fa1f236a)

**Comment by sleepingdragoninn** [comment] 2024-10-01 09:01
duplicate of #170, which I believe is an underlying issue on Surveyor as I've had reports of it happening on hoofprint as well

**Closed as not planned by sleepingdragoninn** 2024-10-01 09:01 UTC
