### ISSUE TITLE
Atlas map not loading with Immersive Portals (Known Issue?)

### ISSUE THREAD

**Issue by Dumpling00** [sleepingdragoninn/antique-atlas#85] opened 2024-04-06 01:59 UTC
> no problem - have fun with atlas!

Oh. and.. well, um. I've heard of this, I guess Immersive Portals and Atlas aren't quite a match just yet.

![image](https://github.com/sisby-folk/antique-atlas/assets/44829013/1e4671ff-b005-4ae5-b17d-ed97fa9de825)

Seems like there's always something, haha.
Can this be fixed in any way, by chance?

_Originally posted by @Dumpling00 in https://github.com/sisby-folk/antique-atlas/issues/84#issuecomment-2040853981_

**Comment by sleepingdragoninn** [comment] 2024-04-06 02:00
duplicate of #69

**Closed as not planned by sleepingdragoninn** 2024-04-06 02:00 UTC

**Comment by Dumpling00** [comment] 2024-04-06 02:01
Sorry! Guess I'm at a dead end then 🤣 
Hopefully this gets solved in the future then! Until then... there goes Immersive Portals haha.
