### ISSUE TITLE
Map resets every time I close the game

### ISSUE THREAD

**Issue by LucasI27** [sleepingdragoninn/antique-atlas#122] opened 2024-05-30 07:03 UTC
Sorry, I can't quite tell what causes this, it doesn't happen every time but, sometimes when I close the game and open back again, the map progress is undone, the markers are still in place but seems like all the previous chunks i've been to are not loaded in the map. I'm playing in a modpack in 1.20.1 btw, may be an incompatibility with another mod, but I can't tell

**Comment by sleepingdragoninn** [comment] 2024-05-31 02:04
Sounds like your UUID is changing - AA uses your UUID to determine map exploration so that players can log into the same instance with different minecraft accounts. This indicates some kind of authentication issue between you and mojang's servers.
You can post your logs/latest.log to https://mclo.gs/ to confirm. if so this is a duplicate of #105

**Comment by sleepingdragoninn** [comment] 2024-06-15 02:03
closed as a likely 105 duplicate - we have intent to fix this for singleplayer via https://github.com/sisby-folk/surveyor/issues/22

**Closed as not planned by sleepingdragoninn** 2024-06-15 02:03 UTC
Labels: incompatibility
