### ISSUE TITLE
Crashes the game while playing on server

### ISSUE THREAD

**Issue by PrejTus** [sleepingdragoninn/antique-atlas#240] opened 2024-10-23 09:19 UTC
I have modded server 1.20.1 on Forge 47.3.0 and if I add any version of Antique Atlas 4 compatible with Minecraft version 1.20.1 to my client it works fine in singleplayer, but if I join my server Im in the game for like 2 seconds (can even open the atlas if im quick) and then I just get the "Saving game..." screen and my client crashes.
The server worked with the mod just fine tommorow. The server was running over night and had 0 players on it.
I even loaded a server backup from tommorow and still, the issue remains.
And I honestly have no idea what to do.

(I have Installed Sinytra Connector, Forgified Fabric API and Surveyor Map Framework)

**Comment by sleepingdragoninn** [comment] 2024-10-23 09:24
Could you do the crash deliberately and then upload and send your logs/latest.log to https://mclo.gs/?

Special request: please don't delete any map save data on the client or server, we've been hunting a bug that might cause this for months but can't reproduce it without a copy of the broken server map data to inspect

**Comment by sleepingdragoninn** [comment] 2024-11-13 05:10
Going to close this as the OP says the server started working again (and therefore there's no valuable save file to salvage)

**Closed as not planned by sleepingdragoninn** 2024-11-13 05:10 UTC
