### ISSUE TITLE
Can't craft the map.

### ISSUE THREAD

**Issue by Gelfa** [sleepingdragoninn/antique-atlas#133] opened 2024-06-11 09:37 UTC
Playing on Fabric 1.20.1, cheked if the mod is installed. It is, searched for the craft, tried and it just does'nt work( Please help.

![Java-runtime-gamma Screenshot 2024 06 11 - 12 35 14 22](https://github.com/sisby-folk/antique-atlas/assets/172377523/3c6a86e2-bb22-49be-8abd-42718eb72f24)
![Java-runtime-gamma Screenshot 2024 06 11 - 12 34 33 20](https://github.com/sisby-folk/antique-atlas/assets/172377523/a000b567-f420-4fb2-889b-00c8a147b13c)
![Java-runtime-gamma Screenshot 2024 06 11 - 12 35 06 83](https://github.com/sisby-folk/antique-atlas/assets/172377523/d15e90e9-c6bb-4b14-98c4-d90c3110ec1f)

**Comment by sleepingdragoninn** [comment] 2024-06-11 09:41
duplicate of #53, #90, #130

**Closed as not planned by sleepingdragoninn** 2024-06-11 09:41 UTC
