### ISSUE TITLE
Wilder Wild's Snowlogging feature can cause a lockup on world load

### ISSUE THREAD

**Issue by pointwoods** [sleepingdragoninn/antique-atlas#106] opened 2024-05-20 22:31 UTC
Visually the loading screen goes to 100%, but it gets stuck there and doesn't ever load into the world, the logs also claim that the spawn area doesn't finish preparing. Unsure what mod could be causing this but I suspect nature's spirit, unsure of that though.
here's my client logs
[latest.log](https://github.com/sisby-folk/antique-atlas/files/15382277/latest.log)

 Any help would be greatly appreciated!!

Edit: replacing the level.dat from my world folder allows me to load into the world, but once it boots up everything is frozen, and im unable to interact with any blocks or look in chests
[latest.log](https://github.com/sisby-folk/antique-atlas/files/15382936/latest.log)
here is the log from that

**Comment by sleepingdragoninn** [comment] 2024-05-21 01:39
Can you confirm this issue doesn't occur without antique atlas? if so, you'll need to bisect your modlist.

**Comment by pointwoods** [comment] 2024-05-21 02:41
yes it only occurs when antique atlas is present, removing it allows me to play

**Comment by sleepingdragoninn** [comment] 2024-05-21 02:43
Can you check if this issue occurs with only atlas installed? youll need to take a world backup ofc or use a fresh world

**Comment by pointwoods** [comment] 2024-05-21 02:49
yes it works with only atlas

**Comment by sleepingdragoninn** [comment] 2024-05-21 02:50
You'll need to identify the specific other mod that breaks atlas in that case

**Comment by pointwoods** [comment] 2024-05-21 04:19
the mod works fine on newly created worlds, just not on my existing one

**Comment by pointwoods** [comment] 2024-05-21 21:40
Okay i narrowed it down to etcetera, it seems to be the issue here, as the world works fine without it

**Comment by sleepingdragoninn** [comment] 2024-05-23 02:28
Can't reproduce this locally - can you create an instance with just atlas and etcetera, reproduce the issue, then post steps and a log to https://mclo.gs/?

**Comment by pointwoods** [comment] 2024-05-23 21:27
as i said before it seems to work fine with any new worlds, its just my existing one that has this problem. I'm unsure what exactly is causing it as even after deleting the region files it still refused to load. I could send the world if that would help at all, but regardless I'll try my best to diagnose the issue myself.

**Comment by pointwoods** [comment] 2024-05-23 22:58
unable to reproduce with only atlas and etcetera, but removing either mod consistently fixes the issue, so I'm not entirely sure what is causing this??

**Comment by invokekitty** [comment] 2024-05-24 12:44
Having the same issue here, cause seems to be Wilder Wild's Snowlogging feature (Mixins related to it appear in the stacktrace and disabling the feature fixes the issue). This is probably an issue on Wilder Wild's side

[latest.log](https://github.com/sisby-folk/antique-atlas/files/15434424/latest.log)
[thread dump.txt](https://github.com/sisby-folk/antique-atlas/files/15434429/thread.dump.txt)

Thread dump generated by ModernFix seems to show the issue at line 1440

**Comment by sleepingdragoninn** [comment] 2024-05-25 11:37
Simple enough - surveyor is generating map data from the chunks as they generate - including getting map colours. Wilder wild is redirecting the map color call and performing operations that cause `getChunkBlocking` to be called (something surveyor deliberately avoids) - this is illegal during load as far as i'm aware, so the whole thing locks up.

**Comment by invokekitty** [comment] 2024-05-25 11:55
im gonna report this to Wilder Wild

**Comment by sleepingdragoninn** [comment] 2024-07-31 10:20
I'm going to close this for now, we'll have to think about if "don't map chunks during spawn preparation" is something we want to change in surveyor later if more issues like this crop up.

**Closed as completed by sleepingdragoninn** 2024-07-31 10:20 UTC
Labels: incompatibility
