### ISSUE TITLE
1.20.1 Atlas 2.9.12

### ISSUE THREAD

**Issue by Krimatoria** [sleepingdragoninn/antique-atlas#172] opened 2024-07-17 02:47 UTC
> 
> [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for jsg:abydos_biome. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> --
> 5665 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:aerglow_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5666 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:aerlavender_fields. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 26 lines
> 5693 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:blazing_dunes. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 3 lines
> 5697 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:blue_aerglow_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 18 lines
> 5716 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for regions_unexplored:chalk_cliffs. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5717 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:chorus_jungle. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 6 lines
> 5724 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:crystal_crags. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 3 lines
> 5728 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_dark_regrowth:deep_light. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5729 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deeperdarker:deeplands. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5730 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for terrablender:deferred_placeholder. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 3 lines
> 5734 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:dragons_den. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5737 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deeperdarker:echoing_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5738 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:elevated_caverns. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5739 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:elevated_clearing. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5740 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:elevated_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 6 lines
> 5747 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:festive_wyndcap_taiga. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 4 lines
> 5752 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:frosted_hills. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 1 line
> 5754 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:frozen_caverns. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 4 lines
> 5759 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for boh:gaster_biome. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 3 lines
> 5763 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:glowshroom_valley. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 1 line
> 5765 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:golden_grove. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5766 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:golden_heights. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 6 lines
> 5773 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for riverredux:gravelly_river. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 5 lines
> 5779 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:holystone_caverns. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 9 lines
> 5789 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for boh:level_0_biome. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 13 lines
> 5803 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:mystic_aerglow_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 3 lines
> 5807 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for blueprint:original_source_marker. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 1 line
> 5809 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deeperdarker:overcast_columns. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 6 lines
> 5816 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:prismarine_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 12 lines
> 5829 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_dark_regrowth:rotten_caverns. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5832 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:sakura_jungle. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5835 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for riverredux:sandy_river. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 4 lines
> 5840 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:sculk_growth. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 1 line
> 5842 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:shattered_end. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 7 lines
> 5850 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:sky_lake. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 5 lines
> 5856 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for aether:skyroot_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5857 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for aether:skyroot_grove. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5858 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:skyroot_jungle. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5859 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for aether:skyroot_meadow. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5860 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for aether:skyroot_woodland. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5863 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:snowy_crimson_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5866 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:snowy_warped_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 7 lines
> 5874 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:sun_forest. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 2 lines
> 5877 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for fokastudio:the_hallow. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 5 lines
> 5883 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for riverredux:tropical_river. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5884 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for regions_unexplored:tropics. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
>   | 15 lines
> 5900 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:wyndcap_highland. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5901 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:wyndcap_peaks. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5902 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for ancient_aether:wyndcap_taiga. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 5903 | [04:39:17] [Render thread/ERROR] [Antique Atlas/]: [Antique Atlas] No fallback could be found for deep_aether:yagroot_swamp. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!
> 
> 
> </body>
> </html>

**Comment by sleepingdragoninn** [comment] 2024-07-17 02:50
duplicate of #83

**Closed as not planned by sleepingdragoninn** 2024-07-17 02:50 UTC
