### ISSUE TITLE
Game crashing upon entering the nether

### ISSUE THREAD

**Issue by GingerPopper** [sleepingdragoninn/antique-atlas#137] opened 2024-06-18 17:09 UTC
My game has been crashing in the nether constantly, in fact, unless I disable the mod and then rejoin I am pretty much soft locked out of the world as long as this mod is still installed. I am using quite a lot of mods and a few mod updates ago I didn't have any issues, it has only recently started to happen. This issue doesn't happen in the overworld, end or any other modded dimension.

Could be some kind of issue from one of the other installed mods, but antique atlas is the one that always shows up in the crash log.
[latest.log](https://github.com/user-attachments/files/15890185/latest.log)

**Comment by sleepingdragoninn** [comment] 2024-06-18 23:53
gonna say this is a duplicate of #138 even though you posted this first, it's easier :P

**Closed as not planned by sleepingdragoninn** 2024-06-18 23:53 UTC
