### ISSUE TITLE
atlas is completley blank for me on 1.21 downloaded from curseforge via prism launcher

### ISSUE THREAD

**Issue by leevee123** [sleepingdragoninn/antique-atlas#176] opened 2024-07-25 08:04 UTC
![image](https://github.com/user-attachments/assets/98a10e8a-ddfb-4565-bf50-44a4ba15fe03)

**Comment by leevee123** [comment] 2024-07-25 08:04
sorry i meant modrinth*** not curseforge, my brain is dumb

**Comment by FractalGeodes** [comment] 2024-07-26 06:19
Same issue occurs for us, we're playing on a multiplayer world without Surveyor on the host

**Comment by leevee123** [comment] 2024-07-26 09:56
> Same issue occurs for us, we're playing on a multiplayer world without Surveyor on the host

yeah same here, but weirdly enough it did randomly start working for some reason and i have no idea why, or what i could have done to make it work

**Comment by FractalGeodes** [comment] 2024-07-27 05:13
I came back again to say that it worked on singleplayer worlds in our testing, but that's interesting. I'll try it again on the same world as before and come back with the results.

edt: It is also now working for us, even on multiplayer. Very odd. I can look through previous logs and see if I can find any issues in them, if needed.

**Comment by sleepingdragoninn** [comment] 2024-07-31 09:05
![image](https://github.com/user-attachments/assets/aa2d4fb1-7337-4bbc-aa15-3e3effe65ee5)

can't reproduce with the same "atlas on client but not server" configuration, and it seems to be solved for both of you, so i'll close this for now - if it happens again, post a fresh issue with a latest.log

**Closed as not planned by sleepingdragoninn** 2024-07-31 09:05 UTC
