### ISSUE TITLE
Why have an option for 1.19.2 if it doesn't even have the atlas?

### ISSUE THREAD

**Issue by asterix728** [sleepingdragoninn/antique-atlas#222] opened 2024-09-18 14:17 UTC
I wanted to get the antique atlas mod for my server with some friends since the map atlases mod on curseforge doesn't work for some reason so i found this, but I don't really see a point of saying there is a version for 1.19.2 if the main attraction of the mod isn't even available

**Comment by sleepingdragoninn** [comment] 2024-09-18 14:47
duplicate of #192 #133 #130 #90 #53

**Closed as not planned by sleepingdragoninn** 2024-09-18 14:47 UTC
