### ISSUE TITLE
Is it compatible with Terralith?

### ISSUE THREAD

**Issue by DracoHero** [sleepingdragoninn/antique-atlas#151] opened 2024-06-29 05:29 UTC
I have a question, will it be compatible with Terralith? I mean... it works for me and everything, but I could make it even more compatible, due to some large messages that appear in the terminal console

**Comment by sleepingdragoninn** [comment] 2024-06-30 06:07
duplicate of #83 - terralith uses real biomes for its terrain, so it's perfectly capable of having a resource pack made for it. Hope so!

**Closed as not planned by sleepingdragoninn** 2024-06-30 06:07 UTC
