### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by AronV4** [sleepingdragoninn/antique-atlas#124] opened 2024-05-31 01:28 UTC
I have curseforge and I try to add this mod for forge 1.20.1 and it doesn't work.

**Comment by AronV4** [comment] 2024-05-31 01:29
In the description it mentions that it works for both fabric and forge.

**Comment by sleepingdragoninn** [comment] 2024-05-31 01:57
> Requires [Connector](https://modrinth.com/mod/connector) and [FFAPI](https://modrinth.com/mod/forgified-fabric-api) on forge.

duplicate of #120 and #108

**Closed as not planned by sleepingdragoninn** 2024-05-31 01:57 UTC
