### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by Kiwifuit** [sleepingdragoninn/antique-atlas#257] opened 2024-12-23 02:04 UTC
I'm trying to install [this version](https://modrinth.com/mod/antique-atlas-4/version/2.10.0+1.20) along with its dependencies and ran my modpack.

It shows up on [the logs](https://paste.ee/p/PwTOu):
```
Mods:
  [✔️] antique-atlas-2.10.0+1.20.jar
  ...
  [✔️] fabric-api-0.83.0+1.20.1.jar
  ...
  [✔️] surveyor-0.6.24+1.20.jar
...

[09:50:34] [main/INFO]: Loading Minecraft 1.20.1 with Quilt Loader 0.27.1
[09:50:34] [main/INFO]: Loading mappings: jar:file:/D:/MultiMC/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar!/mappings/mappings.tiny
[09:50:35] [main/INFO]: Not reusing previous transform cache since it has 448 different keys. (Add '-Dloader.transform_cache.log_changed_keys=true' to see all changes).
transform-cache took 4545ms
zip sub copy took 18ms
tmp jar copy took 0ms
mod adding took 4ms
[09:50:39] [main/INFO]: Loading 57 mods:
| Index | Mod                                       | ID                                   | Version            | Type    | File Hash (SHA-1)                        | File(s)                                                                                 | Sub-File                                                       |
|------:|-------------------------------------------|--------------------------------------|--------------------|---------|------------------------------------------|-----------------------------------------------------------------------------------------|----------------------------------------------------------------|
|    38 | Antique Atlas                             | antique_atlas                        | 2.10.0+1.20        | Fabric  | 8f4c2c18a42625e7a421c53301e6d43c8aa34232 | <mods>\antique-atlas-2.10.0+1.20.jar                                                    |                                                                |
|    41 | Fabric API                                | fabric-api                           | 0.83.0+1.20.1      | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     |                                                                |
|    25 | Fabric API Base                           | fabric-api-base                      | 0.4.29+b04edc7a82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-api-base-0.83.0.jar                      |
|    20 | Fabric API Lookup API (v1)                | fabric-api-lookup-api-v1             | 1.6.34+4d8536c982  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-api-lookup-api-v1-0.83.0.jar             |
|     3 | Fabric Biome API (v1)                     | fabric-biome-api-v1                  | 13.0.10+b3afc78b82 | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-biome-api-v1-0.83.0.jar                  |
|    53 | Fabric Block API (v1)                     | fabric-block-api-v1                  | 1.0.9+e022e5d182   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-block-api-v1-0.83.0.jar                  |
|    31 | Fabric BlockRenderLayer Registration (v1) | fabric-blockrenderlayer-v1           | 1.1.39+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-blockrenderlayer-v1-0.83.0.jar           |
|    56 | Fabric Client Tags                        | fabric-client-tags-api-v1            | 1.0.20+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-client-tags-api-v1-0.83.0.jar            |
|     8 | Fabric Command API (v1)                   | fabric-command-api-v1                | 1.2.32+f71b366f82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-command-api-v1-0.83.0.jar                |
|     5 | Fabric Command API (v2)                   | fabric-command-api-v2                | 2.2.11+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-command-api-v2-0.83.0.jar                |
|     0 | Fabric Commands (v0)                      | fabric-commands-v0                   | 0.2.49+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-commands-v0-0.83.0.jar                   |
|     9 | Fabric Containers (v0)                    | fabric-containers-v0                 | 0.1.61+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-containers-v0-0.83.0.jar                 |
|    40 | Fabric Content Registries (v0)            | fabric-content-registries-v0         | 4.0.7+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-content-registries-v0-0.83.0.jar         |
|    37 | Fabric Convention Tags                    | fabric-convention-tags-v1            | 1.5.3+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-convention-tags-v1-0.83.0.jar            |
|    52 | Fabric Crash Report Info (v1)             | fabric-crash-report-info-v1          | 0.2.18+aeb40ebe82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-crash-report-info-v1-0.83.0.jar          |
|    42 | Fabric Data Generation API (v1)           | fabric-data-generation-api-v1        | 12.1.10+b3afc78b82 | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-data-generation-api-v1-0.83.0.jar        |
|    44 | Fabric Dimensions API (v1)                | fabric-dimensions-v1                 | 2.1.51+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-dimensions-v1-0.83.0.jar                 |
|    19 | Fabric Entity Events (v1)                 | fabric-entity-events-v1              | 1.5.21+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-entity-events-v1-0.83.0.jar              |
|     6 | Fabric Events Interaction (v0)            | fabric-events-interaction-v0         | 0.6.0+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-events-interaction-v0-0.83.0.jar         |
|    28 | Fabric Events Lifecycle (v0)              | fabric-events-lifecycle-v0           | 0.2.61+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-events-lifecycle-v0-0.83.0.jar           |
|    11 | Fabric Game Rule API (v1)                 | fabric-game-rule-api-v1              | 1.0.38+b04edc7a82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-game-rule-api-v1-0.83.0.jar              |
|    29 | Fabric Item API (v1)                      | fabric-item-api-v1                   | 2.1.26+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-item-api-v1-0.83.0.jar                   |
|    51 | Fabric Item Group API (v1)                | fabric-item-group-api-v1             | 4.0.7+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-item-group-api-v1-0.83.0.jar             |
|    27 | Fabric Key Binding API (v1)               | fabric-key-binding-api-v1            | 1.0.36+fb8d95da82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-key-binding-api-v1-0.83.0.jar            |
|    16 | Fabric Key Bindings (v0)                  | fabric-keybindings-v0                | 0.2.34+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-keybindings-v0-0.83.0.jar                |
|     7 | Fabric Lifecycle Events (v1)              | fabric-lifecycle-events-v1           | 2.2.20+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-lifecycle-events-v1-0.83.0.jar           |
|    30 | Fabric Loot API (v2)                      | fabric-loot-api-v2                   | 1.1.37+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-loot-api-v2-0.83.0.jar                   |
|    15 | Fabric Loot Tables (v1)                   | fabric-loot-tables-v1                | 1.1.41+9e7660c682  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-loot-tables-v1-0.83.0.jar                |
|    33 | Fabric Message API (v1)                   | fabric-message-api-v1                | 5.1.6+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-message-api-v1-0.83.0.jar                |
|    22 | Fabric Mining Level API (v1)              | fabric-mining-level-api-v1           | 2.1.47+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-mining-level-api-v1-0.83.0.jar           |
|    12 | Fabric Models (v0)                        | fabric-models-v0                     | 0.3.35+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-models-v0-0.83.0.jar                     |
|    35 | Fabric Networking (v0)                    | fabric-networking-v0                 | 0.3.48+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-networking-v0-0.83.0.jar                 |
|    26 | Fabric Networking API (v1)                | fabric-networking-api-v1             | 1.3.8+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-networking-api-v1-0.83.0.jar             |
|    10 | Fabric Object Builder API (v1)            | fabric-object-builder-api-v1         | 11.0.6+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-object-builder-api-v1-0.83.0.jar         |
|    36 | Fabric Particles (v1)                     | fabric-particles-v1                  | 1.0.28+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-particles-v1-0.83.0.jar                  |
|    43 | Fabric Recipe API (v1)                    | fabric-recipe-api-v1                 | 1.0.18+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-recipe-api-v1-0.83.0.jar                 |
|    45 | Fabric Registry Sync (v0)                 | fabric-registry-sync-v0              | 2.2.6+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-registry-sync-v0-0.83.0.jar              |
|    18 | Fabric Renderer - Indigo                  | fabric-renderer-indigo               | 1.3.1+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-renderer-indigo-0.83.0.jar               |
|     2 | Fabric Renderer API (v1)                  | fabric-renderer-api-v1               | 3.0.1+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-renderer-api-v1-0.83.0.jar               |
|     4 | Fabric Renderer Registries (v1)           | fabric-renderer-registries-v1        | 3.2.44+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-renderer-registries-v1-0.83.0.jar        |
|    14 | Fabric Rendering (v0)                     | fabric-rendering-v0                  | 1.1.47+df3654b382  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-rendering-v0-0.83.0.jar                  |
|    21 | Fabric Rendering (v1)                     | fabric-rendering-v1                  | 3.0.6+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-rendering-v1-0.83.0.jar                  |
|    32 | Fabric Rendering Data Attachment (v1)     | fabric-rendering-data-attachment-v1  | 0.3.33+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-rendering-data-attachment-v1-0.83.0.jar  |
|    24 | Fabric Rendering Fluids (v1)              | fabric-rendering-fluids-v1           | 3.0.26+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-rendering-fluids-v1-0.83.0.jar           |
|    17 | Fabric Resource Conditions API (v1)       | fabric-resource-conditions-api-v1    | 2.3.4+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-resource-conditions-api-v1-0.83.0.jar    |
|    54 | Fabric Resource Loader (v0)               | fabric-resource-loader-v0            | 0.11.7+f7923f6d82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-resource-loader-v0-0.83.0.jar            |
|    23 | Fabric Screen API (v1)                    | fabric-screen-api-v1                 | 2.0.6+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-screen-api-v1-0.83.0.jar                 |
|    13 | Fabric Screen Handler API (v1)            | fabric-screen-handler-api-v1         | 1.3.27+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-screen-handler-api-v1-0.83.0.jar         |
|    39 | Fabric Sound API (v1)                     | fabric-sound-api-v1                  | 1.0.12+b3afc78b82  | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-sound-api-v1-0.83.0.jar                  |
|    34 | Fabric Transfer API (v1)                  | fabric-transfer-api-v1               | 3.2.2+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-transfer-api-v1-0.83.0.jar               |
|    47 | Fabric Transitive Access Wideners (v1)    | fabric-transitive-access-wideners-v1 | 4.2.0+b3afc78b82   | Fabric  | d1a3ff1f25d380f5b991690b2ee983ae4c504759 | <mods>\fabric-api-0.83.0+1.20.1.jar                                                     | /META-INF/jars/fabric-transitive-access-wideners-v1-0.83.0.jar |
|     1 | kaleido-config                            | folk_sisby_kaleido-config            | 0.3.1+1.3.2        | Fabric  | 51b736c3268631e9ebf7526b3dc5d934807d034  | <mods>\surveyor-0.6.24+1.20.jar                                                         | /META-INF/jars/kaleido-config-0.3.1+1.3.2.jar                  |
|    48 | Minecraft                                 | minecraft                            | 1.20.1             | Builtin | 40ecaf8602c0d8765ae0839f5337d1a4a09c9232 | <game>\.cache\quilt_loader\remappedJars\minecraft-1.20.1-0.27.1\client-intermediary.jar | /                                                              |
|       |                                           |                                      |                    |         | 40ecaf8602c0d8765ae0839f5337d1a4a09c9232 | D:\MultiMC\libraries\com\mojang\datafixerupper\6.0.8\datafixerupper-6.0.8.jar           | /                                                              |
|       |                                           |                                      |                    |         | 40ecaf8602c0d8765ae0839f5337d1a4a09c9232 | D:\MultiMC\libraries\com\mojang\authlib\4.0.43\authlib-4.0.43.jar                       | /                                                              |
|       |                                           |                                      |                    |         |                                          | D:\MultiMC\libraries\com\mojang\brigadier\1.1.8\brigadier-1.1.8.jar                     | /                                                              |
|    49 | MixinExtras                               | mixinextras                          | 0.4.1              | Fabric  | bf9be87ff9ed50acb787a821c2ff1ddb3da2522b | D:\MultiMC\libraries\org\quiltmc\quilt-loader\0.27.1\quilt-loader-0.27.1.jar            | /META-INF/jars/mixinextras-fabric-0.4.1.jar                    |
|    50 | OpenJDK 64-Bit Server VM                  | java                                 | 21                 | Builtin |                                          | <user>\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.5.11-hotspot                    |                                                                |
|    46 | Quilt Loader                              | quilt_loader                         | 0.27.1             | Quilt   | bf9be87ff9ed50acb787a821c2ff1ddb3da2522b | D:\MultiMC\libraries\org\quiltmc\quilt-loader\0.27.1\quilt-loader-0.27.1.jar            |                                                                |
|    55 | Surveyor Map Framework                    | surveyor                             | 0.6.24+1.20        | Fabric  | 51b736c3268631e9ebf7526b3dc5d934807d034  | <mods>\surveyor-0.6.24+1.20.jar                                                         |                                                                |
|------:|-------------------------------------------|--------------------------------------|--------------------|---------|------------------------------------------|-----------------------------------------------------------------------------------------|----------------------------------------------------------------|
...
[09:50:58] [Render thread/INFO]: [Antique Atlas] Reloading Tile Textures...
[09:50:58] [Render thread/INFO]: [Antique Atlas] Reloading Biome Tile Providers...
[09:50:58] [Render thread/INFO]: [Antique Atlas] Reloading Marker Textures...
[09:50:58] [Render thread/INFO]: [Antique Atlas] Reloading Structure Tile / Marker Providers...
[09:51:06] [Render thread/INFO]: Loaded 7 recipes
[09:51:06] [Render thread/INFO]: Loaded 1271 advancements
[09:51:11] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 2.079 ms
[09:51:11] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[09:51:11] [Server thread/INFO]: Generating keypair
[09:51:11] [Server thread/INFO]: [Surveyor] Loading data for minecraft:overworld
[09:51:11] [Server thread/INFO]: [Surveyor] Finished loading data for minecraft:overworld
[09:51:14] [Server thread/INFO]: [Surveyor] Loading data for minecraft:the_nether
[09:51:14] [Server thread/INFO]: [Surveyor] Finished loading data for minecraft:the_nether
[09:51:14] [Server thread/INFO]: [Surveyor] Loading data for minecraft:the_end
[09:51:14] [Server thread/INFO]: [Surveyor] Finished loading data for minecraft:the_end
```

but when i try to look for the atlas, either with `/give`, or by looking at the creative inventory, i cant seem to find it. am i doing something wrong?

**Comment by sleepingdragoninn** [comment] 2024-12-23 02:07
missed the description, closing as duplicate of #226 #222 #192 #133 #130 #90 and #53

**Closed as not planned by sleepingdragoninn** 2024-12-23 02:07 UTC
