### ISSUE TITLE
Rehosting to curseforge.

### ISSUE THREAD

**Issue by drakosoldier298** [sleepingdragoninn/antique-atlas#150] opened 2024-06-26 21:49 UTC
I know you say you dont want to rehost it to curseforge and to just add it to the pack and link it but, As far as im aware all mods within curseforge have to be on the website or the modpack gets denied.

**Comment by SplendidAlakey** [comment] 2024-06-28 17:47
No, as long as the license permits it, CF allows including 3rd party mods. The license of this mod is permissive enough for that, but unless the mod is already on the list of approved mods for CF rehosting, you will have to submit it yourself via their support system.

**Comment by sleepingdragoninn** [comment] 2024-06-30 06:05
appreciate the extra info on the process - I'll close this as a duplicate of #80 but let me know if CF denies that request for some reason.

**Closed as not planned by sleepingdragoninn** 2024-06-30 06:05 UTC
