### ISSUE TITLE
Antique Atlas 4 + Big Globe

### ISSUE THREAD

**Issue by Rubinchik11095** [sleepingdragoninn/antique-atlas#256] opened 2024-12-13 10:49 UTC
Hello, I noticed that the Antique Atlas 4 mod is not compatible with the Big Globe mod, I found vesual bugs on the mine map.
Can you please add compatibility of your mod with Big Globe

**Comment by sleepingdragoninn** [comment] 2024-12-13 11:20
duplicate of #83

**Closed as not planned by sleepingdragoninn** 2024-12-13 11:20 UTC

**Comment by Rubinchik11095** [comment] 2024-12-13 12:56
Thanks for the answer, but I don’t remember anything (
