### ISSUE TITLE
add config option to not show player indicator

### ISSUE THREAD

**Issue by SivyxDev** [sleepingdragoninn/antique-atlas#251] opened 2024-11-27 22:48 UTC
adding a config option to disable the player indicator would allow the map to act as a visual supplement rather than as a functional minimap. this would be helpful for cases where players don't want to use a minimap which shows their exact location and want to navigate via the world instead.

**Comment by sleepingdragoninn** [comment] 2024-11-27 23:12
duplicate of #168

**Closed as not planned by sleepingdragoninn** 2024-11-27 23:12 UTC

**Comment by SivyxDev** [comment] 2024-11-27 23:37
understood. I have created a modified version of the mod which roughly implements this for my use. Am I allowed to make this publically available in a modpack? thank you

**Comment by sleepingdragoninn** [comment] 2024-11-27 23:56
LGPLv3! go nuts
