### ISSUE TITLE
Compatibility with other dimensions

### ISSUE THREAD

**Issue by YOUNIN15** [sleepingdragoninn/antique-atlas#128] opened 2024-06-06 12:37 UTC
It would be great if the mod had compatibility with other dimension mods such as The Bumblezone, Ad Astra, Twilight Forest, among others. This would be great.

**Comment by sleepingdragoninn** [comment] 2024-06-06 12:39
duplicate of #83! antique atlas has full support for modded dimensions, but new terrain requires effective resource packing.

**Closed as not planned by sleepingdragoninn** 2024-06-06 12:39 UTC
