### ISSUE TITLE
Antique Atlas cannot render most of Cliff under a Tree's biomes on the map

### ISSUE THREAD

**Issue by FoxySpacy** [sleepingdragoninn/antique-atlas#154] opened 2024-07-01 16:03 UTC
I am not exactly sure why the Atlas couldn't find a fallback for rendering most of Cliff Under a Tree's Biomes on the map, but I am assuming the causes are either because Cliff Under a Tree only had been released recently or that this is a datapack and so Antique Atlas doesn't know how to handle with a datapack. Sorry if this isn't much, I only had just made the account.

**Comment by sleepingdragoninn** [comment] 2024-07-01 22:16
post a log - logs/latest.log to mclo.gs

that'll show what kind of fallback is being used.

**Comment by FoxySpacy** [comment] 2024-07-01 22:18
Can’t do it right now since I am at my part time work. But I will be sure to do it when I can, Thank!

**Comment by FoxySpacy** [comment] 2024-07-02 03:49
[22:59:32] [Render thread/ERROR]: [Antique Atlas] No fallback could be found for clifftree:tundra. This shouldn't happen! This means the biome is not in ANY conventional or vanilla tag on the client!

Here is one of the multiple logs that would show up when I boosted up Minecraft.

**Comment by sleepingdragoninn** [comment] 2024-07-02 04:43
Yep, as indicated, that means the datapack author hasn't put their biomes in any conventional tags. marking this as a duplicate of #83

**Closed as not planned by sleepingdragoninn** 2024-07-02 04:43 UTC
