### ISSUE TITLE
1.19.2 Modpack, Map texture bug

### ISSUE THREAD

**Issue by acquainta** [sleepingdragoninn/antique-atlas#185] opened 2024-08-02 20:47 UTC
So i'm currently running a modpack i created myself on a multiplayer server with some friends and i came across a texture bug which really makes the map quite ugly. It ruins everything and that's so unfortunate because your mod is so nice of an addition to a modpack

![image](https://github.com/user-attachments/assets/d57e2ad5-5c57-4744-b9ff-05a4bc58849b)

I assume it is caused by a world generation mod ? So i guess i should give you every mods i have because i really can't figure out what makes the map look that way

Here's a mega link of all the mods so i don't have to write them all here because there's a lot. If you're willing to find the incompatibility you can also download them

https://mega.nz/folder/wHlV2KAK#NDg7PizhXKYJfr9pKWumkg

**Comment by sleepingdragoninn** [comment] 2024-08-03 05:53
duplicate of #83 - intended behaviour. On newer versions this is handled better, but these are not available for 1.19.2 forge.

**Closed as not planned by sleepingdragoninn** 2024-08-03 05:53 UTC

**Comment by acquainta** [comment] 2024-08-03 09:42
> duplicate of #83 - intended behaviour. On newer versions this is handled better, but these are not available for 1.19.2 forge.

I'm using fabric 1.19.2 and i don't really get what i'm supposed to do to fix it. I don't know how to make a resource pack at all. Do i have to add these biomes in the settings or something for the mod to recognize them i'm confused. Could you help me please ?

**Comment by sleepingdragoninn** [comment] 2024-08-03 09:46
the tag guessing for textures on 1.x should be pretty decent still - post your logs/latest.log to mclo.gs?

**Comment by acquainta** [comment] 2024-08-03 10:03
> the tag guessing for textures on 1.x should be pretty decent still - post your logs/latest.log to mclo.gs?

https://mclo.gs/oFOxkE3
