### ISSUE TITLE
Markers lost on game restart

### ISSUE THREAD

**Issue by Krimatoria** [sleepingdragoninn/antique-atlas#180] opened 2024-07-27 13:35 UTC
2.9.12 Beta

The map mod on the server does not save the map, you have to disconnect to update it. The labels also disappear from the map.

**Comment by Krimatoria** [comment] 2024-07-27 20:26
If I exit Minecraft on the desktop and restart it, enter the world, there will be a map, but without my labels, only the map progress is saved.
![image](https://github.com/user-attachments/assets/81c91331-a5fe-4957-b11b-07afa49ac744)

**Comment by sleepingdragoninn** [comment] 2024-07-31 09:08
I think this is fixed with [latest surveyor](https://modrinth.com/mod/surveyor/changelog) - let me know if not.

if markers are still being lost on restart, please send your logs/latest.log via https://mclo.gs/

**Comment by Krimatoria** [comment] 2024-07-31 12:20
> Думаю, это исправлено в [последней версии Surveyor](https://modrinth.com/mod/surveyor/changelog) . Дайте мне знать, если нет.
> 
> если маркеры все еще теряются при перезапуске, отправьте свои logs/latest.log через https://mclo.gs/

Should it be added to the mods folder along with the atlas too?

**Comment by sleepingdragoninn** [comment] 2024-07-31 14:08
Yes, that will override the version included.

**Comment by Krimatoria** [comment] 2024-08-04 15:13
> Yes, that will override the version included.

I definitely don't see the labels of my friends and the general explored map.

**Comment by Krimatoria** [comment] 2024-08-10 15:24
It would be really great if it was possible to fix this problem...She is still present

> I think this is fixed with [latest surveyor](https://modrinth.com/mod/surveyor/changelog) - let me know if not.
> 
> if markers are still being lost on restart, please send your logs/latest.log via https://mclo.gs/

@sisby-folk

**Comment by sleepingdragoninn** [comment] 2024-10-11 13:53
this sounds like an incompatibility, not a bug - please provide your latest.log via https://mclo.gs/ so i can view the full modlist.

**Comment by sleepingdragoninn** [comment] 2024-11-13 04:55
closing as stale (2 months)

**Closed as not planned by sleepingdragoninn** 2024-11-13 04:55 UTC
Labels: incompatibility
