### ISSUE TITLE
Crash after palette rework in multiplayer only

### ISSUE THREAD

**Issue by ItzLucaGER** [sleepingdragoninn/antique-atlas#143] opened 2024-06-22 15:39 UTC
Game crashes after joining a server. After clearing out the /data/surveyor/ folder you can join just fine. If you then try to rejoin again it doesn't work.

https://mclo.gs/l5zjhTR

Not sure if its an AA or Surveyor issue tho. 
AA verison 2.9.1+1.20
Surveyor version 0.5.1+1.20

I should also say I updated surveyor on the server and client today. This didn't happen in 0.5.0 so it might be a surveyor issue

**Comment by ItzLucaGER** [comment] 2024-06-22 22:01
I just reverted to surveyor 0.5.0 and it seems to be fine

**Comment by ItzLucaGER** [comment] 2024-06-23 20:43
nvm some players still have the issue sometimes. Have to delete the folder everytime to join

**Comment by sleepingdragoninn** [comment] 2024-06-24 01:15
Looks like antique atlas is trying to poll the biome palette for a biome that doesn't exist. Since it only happens on rejoin, it could be an issue with syncing chunks. We'll look into this and see if we need more info.

**Comment by annahla** [comment] 2024-06-24 19:44
this is also happening to me, but clearing out the surveyor folder doesn't work, and the crash happens at the block palette. it started right after updating a bunch of mods, so best guess is that it's due to a removal or addition of blocks or biomes across updates

rolling back does temporarily fix it, but then #134 still fucks shit up ofc

**Comment by ItzLucaGER** [comment] 2024-06-24 20:24
Yes I also updated a bunch of mods, I rolled back surveyor and AA to the second newest version and it seems to be fine most of the time

**Comment by TheD0ct0r101** [comment] 2024-06-24 22:23
This seems to be the same issue members on my server are experiencing, however im not having this issue in singleplayer afaik

**Comment by ItzLucaGER** [comment] 2024-06-24 22:41
could it be an issue with C2ME?

**Comment by TheD0ct0r101** [comment] 2024-06-24 22:54
> could it be an issue with C2ME?

i dont imagine it should be, the error report seems to be purely related to antique atlas. But im no programmer so i could of course be wrong

**Comment by Ethan-C-Honzik** [comment] 2024-06-26 22:31
Same issue here, just updated and now can't join my server worlds. I did confirm that C2ME wasn't causing the issue.

**Comment by Ethan-C-Honzik** [comment] 2024-06-26 22:34
Should also mention I'm running terralith and tectonic together on 1.20.1

**Comment by ItzLucaGER** [comment] 2024-06-26 23:09
its probably one of the mods everyone that has this issue is running that is incompatible with surveyor

**Comment by sleepingdragoninn** [comment] 2024-06-26 23:15
Do please post logs with any +1s, it does help.

For context, we switched to a strict palette system that crashes if a biome that wasn't originally in the registry on load is added. in this case, we're encountering a paletted biome index that isn't in the palette, which is even stranger. 

We made a few fixes in 2.9.3 that are somewhat related, but nothing that would logically solve this issue.

Anyway what we actually need to resolve this is a minimum setup to reproduce the crash - smallest number of mods possible.

**Comment by TheD0ct0r101** [comment] 2024-06-27 02:58
> Do please post logs with any +1s, it does help.
> 
> For context, we switched to a strict palette system that crashes if a biome that wasn't originally in the registry on load is added. in this case, we're encountering a paletted biome index that isn't in the palette, which is even stranger.
> 
> We made a few fixes in 2.9.3 that are somewhat related, but nothing that would logically solve this issue.
> 
> Anyway what we actually need to resolve this is a minimum setup to reproduce the crash - smallest number of mods possible.

I've confirmed the issue still occurs on the latest builds of Antique Atlas (2.9.3) and Surveyor (0.5.3)
While its not exactly a minimal modlist, heres a crash log a server member from my modded server sent me
[message(9).txt](https://github.com/user-attachments/files/16007349/message.9.txt)

I also would like to confirm with you, is surveyor even needed? I ran Antique Atlas without Surveyor not long ago and it ran fine.

**Comment by sleepingdragoninn** [comment] 2024-06-27 04:32
in antique atlas 1.x the backend for antique atlas was inside antique atlas (saving, scanning, etc), in 2.x we completely deleted that and replaced it with surveyor, which we wrote for the purpose. So yep, from 2.0, completely required - it's what enabled the mod to be rebuilt as client-side at all.

**Comment by sleepingdragoninn** [comment] 2024-06-27 04:33
Anyway, you'll need to bisect to find the issue - without a minimum modset it's not possible for me to debug.

**Comment by TheD0ct0r101** [comment] 2024-06-27 08:28
> in antique atlas 1.x the backend for antique atlas was inside antique atlas (saving, scanning, etc), in 2.x we completely deleted that and replaced it with surveyor, which we wrote for the purpose. So yep, from 2.0, completely required - it's what enabled the mod to be rebuilt as client-side at all.

Weird, I ran Antique Atlas 4 2.9.1 without Surveyor just fine. Ah well. Ill do some testing later

**Comment by sleepingdragoninn** [comment] 2024-06-30 10:30
Can you try this with surveyor 0.5.4? we've made a few corrections.

**Comment by ItzLucaGER** [comment] 2024-06-30 13:18
Will do, does 0.5.4 need to be only on the server or client too?

**Comment by sleepingdragoninn** [comment] 2024-06-30 13:34
both

**Comment by limelier** [comment] 2024-08-23 13:54
Also ran into a nether-related crash, like in #129. I'm not entirely sure if it's the same issue as this one, but it did match part of the crash log in #129.

Crashed when traveling to the nether on a multiplayer server. Also crash every time I try to reconnect. Clearing the Surveyor data did not seem to help.

I'm playing on 1.20.1, running AA4 2.9.13+1.20 and Surveyor 0.6.22+1.20 (also occurs on 0.6.21) on NeoForge 47.1.106 through Sinytra Connector 1.0.0-beta.44+1.20.1 along with [a bunch of other mods](https://modrinth.com/modpack/towering-isles).

[crash-2024-08-23_16.43.51-client.txt](https://github.com/user-attachments/files/16729660/crash-2024-08-23_16.43.51-client.txt)

Still trying to figure out how to connect back to the server without removing Antique Atlas. Let me know if you need anything else.

edit: Tested in a singleplayer world, crash does not occur, even on the same seed and position.

**Comment by limelier** [comment] 2024-08-23 14:17
Huh. I removed Antique Atlas temporarily so I could connect and exit the nether. Upon adding it back in, crash no longer occurs, even if I go to the nether.

**Comment by limelier** [comment] 2024-08-23 19:59
I just had someone else go through similar steps (go to nether, crash, disable AA, rejoin, don't crash, re-enable AA) but it didn't work, they still crashed. Maybe removing and re-adding the surveyor data in-between made the difference for me?

edit: Okay, it seems a bit inconsistent. A second friend managed to go into the nether without an AA crash. Later, we both crashed due to unrelated reasons, and when we came back, both of us (him with no prior crashes, me with the workaround above) started crashing again.

edit 2: Yeah, I don't know. It looks like there's a way the crashes start (something related to coming into the nether? crashing while in the nether?), they continue for as long as AA is enabled in the nether, and then stop somehow (when you leave the nether, re-enable AA and come back? when you mess with the Surveyor data? not sure).

**Comment by limelier** [comment] 2024-08-24 09:21
I made a PR to fix my problem - I don't think it's related to this issue after all. My bad.

**Comment by sleepingdragoninn** [comment] 2024-09-09 05:24
closing this in favour of #208

**Closed as not planned by sleepingdragoninn** 2024-09-09 05:24 UTC
Labels: bug, incompatibility
