### ISSUE TITLE
Server crash [Forge] [1.20.1]

### ISSUE THREAD

**Issue by MaxWasUnavailable** [sleepingdragoninn/antique-atlas#182] opened 2024-07-29 15:02 UTC
Crash report: https://pastebin.com/Bvf0egRC
Antique Atlas version: 2.9.12
Minecraft version: 1.20.1
Forge version: 47.3.4
Sinytra version: 1.0.0-beta.44-1.20.1

**Comment by sleepingdragoninn** [comment] 2024-07-31 09:12
dupe of #160

**Closed as not planned by sleepingdragoninn** 2024-07-31 09:12 UTC
